Repository KusitmsHDmedi/HDmedi_Android, pull requests merged in 2023-09, with the labels that each got.

#5 [FIX] gitignore 파일 수정
  .gitignore
  .idea/.gitignore
  .idea/.name
  .idea/compiler.xml
  .idea/deploymentTargetDropDown.xml
  .idea/gradle.xml
  .idea/kotlinc.xml
  .idea/misc.xml
  .idea/vcs.xml
Labels: 승구, fix

#8 [FEAT] 네이버 로그인 구현
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/hdmedi/activity/LoginActivity.kt
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/values/strings.xml
Labels: 승구, feat

#13 Feat. OnBoarding UI 구현
  app/src/main/java/com/example/hdmedi/activity/BindingActivity.kt
  app/src/main/java/com/example/hdmedi/activity/OnBoardingActivity.kt
  app/src/main/res/drawable/button_background.xml
  app/src/main/res/drawable/button_background_activated.xml
  app/src/main/res/drawable/button_selector.xml
  app/src/main/res/drawable/cardview_selector.xml
  app/src/main/res/drawable/ic_circle1.png
  app/src/main/res/drawable/ic_circle2.png
  app/src/main/res/drawable/ic_parent.png
  app/src/main/res/drawable/ic_teacher.png
  app/src/main/res/drawable/logo.png
  app/src/main/res/font/pretendard_medium.otf
  app/src/main/res/font/pretendard_semibold.otf
  app/src/main/res/layout/activity_on_boarding.xml
  app/src/main/res/values/colors.xml
Labels: 승구, feat

#15 Feat. 스플래쉬 화면 배경 색상, 로고 이미지 설정
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/hdmedi/activity/SplashActivity.kt
  app/src/main/res/layout/activity_splash.xml
Labels: 승구, feat

#18 [Feat] 자녀 정보 입력 UI 구현 및 로그인 UI 수정
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/hdmedi/activity/BirthPickerDialog.kt
  app/src/main/java/com/example/hdmedi/activity/LoginActivity.kt
  app/src/main/java/com/example/hdmedi/activity/OnBoardingActivity.kt
  app/src/main/java/com/example/hdmedi/activity/ParentsSettingActivity.kt
  app/src/main/res/drawable/dialog_background.xml
  app/src/main/res/drawable/female_icon.png
  app/src/main/res/drawable/gender_button_activated.xml
  app/src/main/res/drawable/gender_button_selector.xml
  app/src/main/res/drawable/ic_back.png
  app/src/main/res/drawable/ic_calendar.png
  app/src/main/res/drawable/ic_female.xml
  app/src/main/res/drawable/ic_male.xml
  app/src/main/res/drawable/ic_naver.png
  app/src/main/res/drawable/ic_naver.xml
  app/src/main/res/drawable/male_icon.png
  app/src/main/res/drawable/naver.png
  app/src/main/res/font/pretendard_bold.otf
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_on_boarding.xml
  app/src/main/res/layout/activity_parents_setting.xml
  app/src/main/res/layout/birth_picker_dialog.xml
  settings.gradle
Labels: 승구, feat

#21 [Feat] 교사 온보딩 UI 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/hdmedi/activity/CheckInfoActivity.kt
  app/src/main/java/com/example/hdmedi/activity/OnBoardingActivity.kt
  app/src/main/java/com/example/hdmedi/activity/TeacherSettingActivity.kt
  app/src/main/res/drawable/ic_child.png
  app/src/main/res/drawable/ic_parent.png
  app/src/main/res/drawable/ic_teacher.png
  app/src/main/res/layout/activity_check_info.xml
  app/src/main/res/layout/activity_on_boarding.xml
  app/src/main/res/layout/activity_teacher_setting.xml
Labels: 승구, feat

#22 [Feat] 검사 요청 UI 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/hdmedi/activity/BaseActivity.kt
  app/src/main/java/com/example/hdmedi/activity/BindingActivity.kt
  app/src/main/java/com/example/hdmedi/activity/BirthPickerDialog.kt
  app/src/main/java/com/example/hdmedi/activity/CheckInfoActivity.kt
  app/src/main/java/com/example/hdmedi/activity/OnBoardingActivity.kt
  app/src/main/java/com/example/hdmedi/activity/ParentsSettingActivity.kt
  app/src/main/java/com/example/hdmedi/activity/RequestDialog.kt
  app/src/main/java/com/example/hdmedi/activity/RequestResultParentActivity.kt
  app/src/main/java/com/example/hdmedi/activity/TeacherSettingActivity.kt
  app/src/main/res/drawable/no_button_background.xml
  app/src/main/res/drawable/request_dialog_background.xml
  app/src/main/res/layout/activity_request_result_parent.xml
  app/src/main/res/layout/dialog_birth_picker.xml
  app/src/main/res/layout/dialog_request.xml
Labels: 승구, feat, refactor

#24 [Feat] 검사 결과 전송 완료 UI 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/hdmedi/activity/RequestResultParentActivity.kt
  app/src/main/java/com/example/hdmedi/activity/SendResultActivity.kt
  app/src/main/res/drawable/ic_result.png
  app/src/main/res/layout/activity_request_result_parent.xml
  app/src/main/res/layout/activity_send_result.xml
  app/src/main/res/layout/dialog_request.xml
Labels: 승구, feat

#26 [Feat] 나가기 Dialog 구현
  app/src/main/java/com/example/hdmedi/activity/ExitDialog.kt
  app/src/main/res/drawable/exit_button_background.xml
  app/src/main/res/layout/dialog_exit.xml
Labels: 승구, feat

#32 [Fix] 아이 코드 입력 UI의 다음 버튼 텍스트의 폰트, 색상, 크기 수정
  app/src/main/java/com/example/hdmedi/activity/TeacherSettingActivity.kt
  app/src/main/res/layout/activity_teacher_setting.xml
  app/src/main/res/values/colors.xml
Labels: 승구, fix

#34 [Feat] 홈 UI 구현
  app/src/main/java/com/example/hdmedi/activity/MainActivity.kt
  app/src/main/res/drawable/ic_alarm.png
  app/src/main/res/drawable/ic_child2.png
  app/src/main/res/drawable/ic_document.png
  app/src/main/res/drawable/ic_pen.png
  app/src/main/res/drawable/logo2.png
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/values/colors.xml
Labels: 승구, feat

#36 Feat. 검사 기능 추가
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/hdmedi/ResultAdapter.kt
  app/src/main/java/com/example/hdmedi/activity/MainActivity.kt
  app/src/main/java/com/example/hdmedi/fragment/Result1Fragment.kt
  app/src/main/java/com/example/hdmedi/fragment/Result2Fragment.kt
  app/src/main/java/com/example/hdmedi/fragment/Test2To18Fragment.kt
  app/src/main/java/com/example/hdmedi/fragment/TestFragment.kt
  app/src/main/java/com/example/hdmedi/fragment/TestStartFragment.kt
  app/src/main/java/com/example/hdmedi/model/resultData.kt
  app/src/main/java/com/example/hdmedi/resultViewModel.kt
  app/src/main/res/drawable/check.xml
  app/src/main/res/drawable/girl.png
  app/src/main/res/drawable/preimage.xml
  app/src/main/res/drawable/progress10.xml
  app/src/main/res/drawable/progress11.xml
  app/src/main/res/drawable/progress12.xml
  app/src/main/res/drawable/progress13.xml
  app/src/main/res/drawable/progress14.xml
  app/src/main/res/drawable/progress15.xml
  app/src/main/res/drawable/progress16.xml
  app/src/main/res/drawable/progress17.xml
  app/src/main/res/drawable/progress18.xml
  app/src/main/res/drawable/progress2.xml
  app/src/main/res/drawable/progress3.xml
  app/src/main/res/drawable/progress4.xml
  app/src/main/res/drawable/progress5.xml
  app/src/main/res/drawable/progress6.xml
  app/src/main/res/drawable/progress7.xml
  app/src/main/res/drawable/progress8.xml
  app/src/main/res/drawable/progress9.xml
  app/src/main/res/drawable/progressbar1.xml
  app/src/main/res/drawable/startbtn.xml
  app/src/main/res/drawable/uncheck.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_result1.xml
  app/src/main/res/layout/fragment_result2.xml
  app/src/main/res/layout/fragment_test.xml
  app/src/main/res/layout/fragment_test2_to18.xml
  app/src/main/res/layout/fragment_test_start.xml
  app/src/main/res/layout/rv_result_item.xml
  app/src/main/res/values/strings.xml
Labels: add, 승균, feat, fix

#39 [Add] HomeActivity 추가
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/hdmedi/activity/HomeActivity.kt
  app/src/main/res/layout/activity_home.xml
Labels: add, 승구

#41 Fix. 화면 비율 수정 및 답변 수정
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/hdmedi/activity/ParentsSettingActivity.kt
  app/src/main/java/com/example/hdmedi/fragment/Result2Fragment.kt
  app/src/main/java/com/example/hdmedi/fragment/Test2To18Fragment.kt
  app/src/main/res/drawable/main.png
  app/src/main/res/layout/fragment_result2.xml
  app/src/main/res/layout/fragment_test2_to18.xml
  app/src/main/res/layout/fragment_test_start.xml
Labels: add, fix

#42 Feat. 이전 버튼 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/hdmedi/fragment/Result2Fragment.kt
  app/src/main/java/com/example/hdmedi/fragment/Test2To18Fragment.kt
  app/src/main/java/com/example/hdmedi/fragment/TestFragment.kt
  app/src/main/java/com/example/hdmedi/resultViewModel.kt
  app/src/main/res/layout/fragment_result1.xml
Labels: feat

#43 Fix. 디자인 수정
  app/src/main/res/layout/fragment_test.xml
  app/src/main/res/layout/fragment_test2_to18.xml
  app/src/main/res/layout/fragment_test_start.xml
Labels: 승구, fix

#44 [Fix] UI 수정 및 ExitDialog 연결
  app/src/main/java/com/example/hdmedi/activity/ExitDialog.kt
  app/src/main/java/com/example/hdmedi/activity/RequestDialog.kt
  app/src/main/java/com/example/hdmedi/fragment/Result1Fragment.kt
  app/src/main/java/com/example/hdmedi/fragment/Test2To18Fragment.kt
  app/src/main/java/com/example/hdmedi/fragment/TestFragment.kt
  app/src/main/res/layout/dialog_exit.xml
  app/src/main/res/layout/dialog_request.xml
  app/src/main/res/layout/fragment_test.xml
  app/src/main/res/layout/fragment_test2_to18.xml
  app/src/main/res/layout/fragment_test_start.xml
  app/src/main/res/values/colors.xml
Labels: 승구, feat, fix

#46 [Fix] 검사 결과 UI 수정
  app/src/main/AndroidManifest.xml
  app/src/main/res/layout/fragment_result1.xml
  app/src/main/res/layout/rv_result_item.xml
Labels: 승구, fix

#50 [Feat] 검사 결과 비교 UI 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/hdmedi/CompareResultAdapter.kt
  app/src/main/java/com/example/hdmedi/ResultAdapter.kt
  app/src/main/java/com/example/hdmedi/activity/DetailResultActivity.kt
  app/src/main/java/com/example/hdmedi/activity/ResultCompareActivity.kt
  app/src/main/java/com/example/hdmedi/fragment/Result1Fragment.kt
  app/src/main/res/layout/activity_detail_result.xml
  app/src/main/res/layout/activity_result_compare.xml
  app/src/main/res/layout/fragment_result1.xml
  app/src/main/res/layout/result_item.xml
  app/src/main/res/layout/rv_result_item.xml
  app/src/main/res/values/strings.xml
Labels: 승구, feat

#52 [Fix] UI 수정
  app/build.gradle
  app/src/main/java/com/example/hdmedi/activity/CheckInfoActivity.kt
  app/src/main/java/com/example/hdmedi/activity/HomeActivity.kt
  app/src/main/java/com/example/hdmedi/activity/ParentsSettingActivity.kt
  app/src/main/java/com/example/hdmedi/activity/SplashActivity.kt
  app/src/main/java/com/example/hdmedi/activity/TeacherSettingActivity.kt
  app/src/main/java/com/example/hdmedi/fragment/Result2Fragment.kt
  app/src/main/java/com/example/hdmedi/retrofit/RetrofitInstance.kt
  app/src/main/java/com/example/hdmedi/sharedPreference/MyApplication.kt
  app/src/main/java/com/example/hdmedi/sharedPreference/PreferenceUtil.kt
  app/src/main/res/drawable/ic_girl.png
  app/src/main/res/layout/activity_home.xml
  app/src/main/res/layout/fragment_result1.xml
  app/src/main/res/layout/fragment_result2.xml
Labels: 승구, fix

#54 Feat. API 추가
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/hdmedi/activity/BirthPickerDialog.kt
  app/src/main/java/com/example/hdmedi/activity/HomeActivity.kt
  app/src/main/java/com/example/hdmedi/activity/LoginActivity.kt
  app/src/main/java/com/example/hdmedi/activity/ParentsSettingActivity.kt
  app/src/main/java/com/example/hdmedi/fragment/Test2To18Fragment.kt
  app/src/main/java/com/example/hdmedi/model/SignInResponseBody.kt
  app/src/main/java/com/example/hdmedi/retrofit/APIS.kt
Labels: add, 승균, feat, fix

#57 [Fix] 디자인 QA 반영#1
  app/src/main/java/com/example/hdmedi/activity/HomeActivity.kt
  app/src/main/java/com/example/hdmedi/activity/LoginActivity.kt
  app/src/main/java/com/example/hdmedi/activity/ParentsSettingActivity.kt
  app/src/main/java/com/example/hdmedi/activity/RequestDialog.kt
  app/src/main/java/com/example/hdmedi/activity/RequestResultParentActivity.kt
  app/src/main/java/com/example/hdmedi/activity/SendResultActivity.kt
  app/src/main/java/com/example/hdmedi/fragment/Result2Fragment.kt
  app/src/main/java/com/example/hdmedi/fragment/Test2To18Fragment.kt
  app/src/main/java/com/example/hdmedi/fragment/TestStartFragment.kt
  app/src/main/java/com/example/hdmedi/retrofit/APIS.kt
  app/src/main/res/drawable/main_boy.png
  app/src/main/res/drawable/main_girl.png
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_parents_setting.xml
  app/src/main/res/layout/activity_send_result.xml
  app/src/main/res/layout/fragment_result2.xml
  app/src/main/res/layout/fragment_test_start.xml
Labels: 승구, fix, refactor

#59 [Feat] API 연동#1
  app/src/main/java/com/example/hdmedi/activity/CheckInfoActivity.kt
  app/src/main/java/com/example/hdmedi/activity/RequestResultParentActivity.kt
  app/src/main/java/com/example/hdmedi/activity/TeacherSettingActivity.kt
  app/src/main/java/com/example/hdmedi/fragment/Test2To18Fragment.kt
  app/src/main/java/com/example/hdmedi/model/SurveyRequestBody.kt
  app/src/main/res/layout/activity_check_info.xml
  app/src/main/res/layout/activity_request_result_parent.xml
  app/src/main/res/layout/activity_teacher_setting.xml
Labels: 승구, feat

#61 Feat. api 연동
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/hdmedi/SurveyAllAdapter.kt
  app/src/main/java/com/example/hdmedi/SurveyAllViewModel.kt
  app/src/main/java/com/example/hdmedi/activity/CheckResultActivity.kt
  app/src/main/java/com/example/hdmedi/activity/DetailResultActivity.kt
  app/src/main/java/com/example/hdmedi/activity/ParentsSettingActivity.kt
  app/src/main/java/com/example/hdmedi/model/SurveyAllResponseBody.kt
  app/src/main/java/com/example/hdmedi/model/SurveyDetailResponseModel.kt
  app/src/main/java/com/example/hdmedi/retrofit/APIS.kt
  app/src/main/res/drawable/gogo.xml
  app/src/main/res/layout/activity_check_result.xml
  app/src/main/res/layout/activity_detail_result.xml
  app/src/main/res/layout/rv_item_surveyall.xml
Labels: add, 승균, feat, fix, refactor, del

#63 [Feat] 앱 아이콘 설정
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/hdmedi/activity/CheckInfoActivity.kt
  app/src/main/java/com/example/hdmedi/activity/HomeActivity.kt
  app/src/main/java/com/example/hdmedi/activity/ParentsSettingActivity.kt
  app/src/main/java/com/example/hdmedi/activity/TeacherSettingActivity.kt
  app/src/main/java/com/example/hdmedi/model/GuestSignInResponseBody.kt
  app/src/main/res/drawable/ic_app.png
  app/src/main/res/drawable/ic_app_round.png
  app/src/main/res/layout/activity_check_info.xml
Labels: 승구, feat

#65 [Feat] 이전 검사 결과 확인 API 연결
  app/src/main/java/com/example/hdmedi/SurveyAllAdapter.kt
  app/src/main/java/com/example/hdmedi/activity/CheckResultActivity.kt
  app/src/main/java/com/example/hdmedi/activity/DetailResultActivity.kt
  app/src/main/java/com/example/hdmedi/model/SurveyDetailResponseModel.kt
  app/src/main/res/layout/activity_detail_result.xml
  app/src/main/res/layout/rv_item_surveyall.xml
Labels: 승구, feat, fix

#69 [Update] ReadMe 작성
  README.md
Labels: add, 승구
